name: Release Draft

on:
  push:
    branches:
      - main
    paths:
      - 'pom.xml'

jobs:
  release-draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Execute Python script
        run: python .github/scripts/pom_version_checker.py
